# Generated by Django 4.2.4 on 2023-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdForm',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stdform',
                'managed': False,
            },
        ),
    ]
