# Generated by Django 4.2.4 on 2023-10-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdNum', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StdForm',
        ),
    ]
